the dataset has a license-CC-SA-BY-NC
-creative common so give a credit to
-share alike
-non comercial

In [1]:
!git clone https://github.com/august2011/Decision_trees.git

Cloning into 'Decision_trees'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 18 (delta 4), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (18/18), 5.77 KiB | 1.44 MiB/s, done.


In [3]:
from google.colab.drive import mount
mount("/content/drive")

Mounted at /content/drive


In [4]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split,StratifiedKFold
from imblearn.over_sampling import RandomOverSampler
from sklearn.feature_selection import SelectKBest,f_classif
from sklearn.metrics import accuracy_score,f1_score,recall_score,precision_score,roc_auc_score,confusion_matrix

In [5]:
pd.__version__,np.__version__

('1.5.3', '1.22.4')

In [6]:
df=pd.read_csv("/content/drive/MyDrive/cn240/final/data/data.csv")
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

#EDA 📊

In [7]:
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [8]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [9]:
df.isna().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [10]:
# see what is 'Unnamed: 32'
df["Unnamed: 32"]
#all NaN so drop this

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
564   NaN
565   NaN
566   NaN
567   NaN
568   NaN
Name: Unnamed: 32, Length: 569, dtype: float64

In [11]:
df=df.drop(["Unnamed: 32","id"],axis=1)

In [12]:
df.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [13]:
#see diagnosis
print(df.value_counts("diagnosis"))

diagnosis
B    357
M    212
dtype: int64


#Feature selection using selecKBest 🥘

In [14]:
##not work
#from sklearn.feature_selection import SelectKBest,f_classif

In [15]:
selected=SelectKBest(f_classif, k=10).fit(df.iloc[:,1:],df.iloc[:,0])

In [16]:
print(selected.scores_)
print(df.iloc[:,1:].columns)

[6.46981021e+02 1.18096059e+02 6.97235272e+02 5.73060747e+02
 8.36511234e+01 3.13233079e+02 5.33793126e+02 8.61676020e+02
 6.95274435e+01 9.34592949e-02 2.68840327e+02 3.90947023e-02
 2.53897392e+02 2.43651586e+02 2.55796780e+00 5.32473391e+01
 3.90144816e+01 1.13262760e+02 2.41174067e-02 3.46827476e+00
 8.60781707e+02 1.49596905e+02 8.97944219e+02 6.61600206e+02
 1.22472880e+02 3.04341063e+02 4.36691939e+02 9.64385393e+02
 1.18860232e+02 6.64439606e+01]
Index(['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean',
       'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave 

In [17]:
x=df.drop("diagnosis",axis=1)

In [18]:
x=list(x)
selected=list(selected.scores_)

In [19]:
top=pd.DataFrame(x,selected,columns=["columns"])
top10=top.sort_index(ascending=False).head(10)
top10_columns=list(top10["columns"])

In [20]:
top10

columns
964.385393  concave points_worst
897.944219       perimeter_worst
861.676020   concave points_mean
860.781707          radius_worst
697.235272        perimeter_mean
661.600206            area_worst
646.981021           radius_mean
573.060747             area_mean
533.793126        concavity_mean
436.691939       concavity_worst

In [21]:
top10_columns

['concave points_worst',
 'perimeter_worst',
 'concave points_mean',
 'radius_worst',
 'perimeter_mean',
 'area_worst',
 'radius_mean',
 'area_mean',
 'concavity_mean',
 'concavity_worst']

#try phase 2 :7,8,9

##prepare data using train_test_split, oversampling and balancing 5-fold

In [22]:
#212 malignane ,357 bening

In [23]:
def to_0_1(x):
  if x=="M":
    return 1
  else: 
    return 0

In [24]:
df["diagnosis"]=df["diagnosis"].apply(lambda x: to_0_1(x))

In [25]:

df_train,df_test=train_test_split(df,test_size=0.25,random_state=230,shuffle=True)

In [26]:
df_test.value_counts("diagnosis")

diagnosis
0    88
1    55
dtype: int64

In [27]:
#in df_test do not care balancing
df_train.shape,df_test.shape

((426, 31), (143, 31))

In [28]:
df_train.value_counts("diagnosis",)
#so try over sampling on 1,benign 

diagnosis
0    269
1    157
dtype: int64

In [29]:

ros = RandomOverSampler(random_state=0)
x_train,y_train = ros.fit_resample(df_train.drop("diagnosis",axis=1),df_train["diagnosis"])

In [30]:
#we got the balanced df_train
y_train.value_counts()

0    269
1    269
Name: diagnosis, dtype: int64

In [31]:
x_train.shape,y_train.shape

((538, 30), (538,))

In [32]:
df_train=x_train
df_train["diagnosis"]=y_train

In [33]:
skf = StratifiedKFold(n_splits=5,random_state=11,shuffle=True,)
f1,f2,f3,f4,f5=skf.split(x_train, y_train)
list_fold=[f1,f2,f3,f4,f5]
def show_each_fold(list_fold):
  count=0
  for i in list_fold:
    print(f"fold: {count}")
    print(y_train[list(i[0])].value_counts(),y_train[list(i[1])].value_counts())
    count+=1
show_each_fold(list_fold)

fold: 0
0    215
1    215
Name: diagnosis, dtype: int64 0    54
1    54
Name: diagnosis, dtype: int64
fold: 1
0    215
1    215
Name: diagnosis, dtype: int64 0    54
1    54
Name: diagnosis, dtype: int64
fold: 2
0    215
1    215
Name: diagnosis, dtype: int64 0    54
1    54
Name: diagnosis, dtype: int64
fold: 3
1    216
0    215
Name: diagnosis, dtype: int64 0    54
1    53
Name: diagnosis, dtype: int64
fold: 4
0    216
1    215
Name: diagnosis, dtype: int64 1    54
0    53
Name: diagnosis, dtype: int64


##7:1'st method but every thing every where all at once 🧙‍♂️


In [34]:
!python -m pip install autogluon

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 218.3/218.3 kB 14.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.1/60.1 kB 9.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 292.2/292.2 kB 24.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 32.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.7/108.7 kB 15.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 91.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.6/135.6 kB 18.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 3.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.4/57.4 MB 12.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 74.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.4/90.4 kB 15.1 MB/s eta 0:00:00
     ━━━━━━━━━━━

In [35]:
from autogluon.tabular import TabularDataset, TabularPredictor

In [36]:
train=df

In [37]:
predictor = TabularPredictor(label="diagnosis",).fit(train)

No path specified. Models will be saved in: "AutogluonModels/ag-20230512_155512/"
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20230512_155512/"
AutoGluon Version:  0.7.0
Python Version:     3.10.11
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Sat Dec 10 16:00:40 UTC 2022
Train Data Rows:    569
Train Data Columns: 30
Label Column: diagnosis
Preprocessing data ...
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [1, 0]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    12062.73 MB
	Train Data (Origina

In [38]:
#got WeightedEnsemble_L2 the best val_score==0.9912 accuracy
predictor.get_model_best()

'WeightedEnsemble_L2'

### to deep thought with deep 🐙

In [39]:
#see the test df
df_test

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
519          0        12.75         16.70           82.51      493.8   
189          0        12.30         15.90           78.83      463.7   
277          1        18.81         19.98          120.90     1102.0   
147          0        14.95         18.77           97.84      689.5   
283          1        16.24         18.77          108.80      805.1   
..         ...          ...           ...             ...        ...   
431          0        12.40         17.68           81.47      467.8   
558          0        14.59         22.68           96.39      657.1   
78           1        20.18         23.97          143.70     1245.0   
280          1        19.16         26.60          126.20     1138.0   
362          0        12.76         18.84           81.87      496.6   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
519          0.11250           0.11170         0.03880              0.02995   
189          0.08080           0.07253         0.03844              0.01654   
277          0.08923           0.05884         0.08020              0.05843   
147          0.08138           0.11670         0.09050              0.03562   
283          0.10660           0.18020         0.19480              0.09052   
..               ...               ...             ...                  ...   
431          0.10540           0.13160         0.07741              0.02799   
558          0.08473           0.13300         0.10290              0.03736   
78           0.12860           0.34540         0.37540              0.16040   
280          0.10200           0.14530         0.19210              0.09664   
362          0.09676           0.07952         0.02688              0.01781   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
519         0.2120  ...         14.45          21.74            93.63   
189         0.1667  ...         13.35          19.59            86.65   
277         0.1550  ...         19.96          24.30           129.00   
147         0.1744  ...         16.25          25.47           107.10   
283         0.1876  ...         18.55          25.09           126.90   
..             ...  ...           ...            ...              ...   
431         0.1811  ...         12.88          22.91            89.61   
558         0.1454  ...         15.48          27.27           105.90   
78          0.2906  ...         23.37          31.72           170.30   
280         0.1902  ...         23.72          35.90           159.80   
362         0.1759  ...         13.75          25.99            87.82   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
519       624.1            0.1475             0.1979           0.1423   
189       546.7            0.1096             0.1650           0.1423   
277      1236.0            0.1243             0.1160           0.2210   
147       809.7            0.0997             0.2521           0.2500   
283      1031.0            0.1365             0.4706           0.5026   
..          ...               ...                ...              ...   
431       515.8            0.1450             0.2629           0.2403   
558       733.5            0.1026             0.3171           0.3662   
78       1623.0            0.1639             0.6164           0.7681   
280      1724.0            0.1782             0.3841           0.5754   
362       579.7            0.1298             0.1839           0.1255   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
519               0.08045          0.3071                  0.08557  
189               0.04815          0.2482                  0.06306  
277               0.12940          0.2567                  0.05737  
147               0.08405          0.2852                  0.09218  
283               0.17320          0.2770                  0.10630  
..                    .

In [40]:
df_test.value_counts("diagnosis")

diagnosis
0    88
1    55
dtype: int64

In [41]:
train_data = TabularDataset(df_train)
test_data= TabularDataset(df_test)
metric = 'accuracy'
y_true=test_data["diagnosis"]
test_data=test_data.drop("diagnosis",axis=1)

In [42]:
accuracy_score(y_true,predictor.predict(test_data,model=predictor.get_model_best()))

0.993006993006993

###set hyperparameters for training

In [43]:
import autogluon.core as ag
import random
import numpy as np
import torch
torch.manual_seed(0)
random.seed(0)
np.random.seed(0)

nn_options = {
    'num_epochs': 10, 
    'learning_rate': ag.space.Real(1e-4, 1e-2, default=5e-4, log=True),
    'activation': ag.space.Categorical('relu', 'softrelu', 'tanh'),
    'dropout_prob': ag.space.Real(0.0, 0.5, default=0.1)
}
gbm_options = { 
    'num_boost_round': 100,
    'num_leaves': ag.space.Int(lower=36, upper=66, default=36),
}
cat_options={
    'iterations':100,
    'learning_rate': 0.1,
    'depth':6
}
xg_options={
    'max_depth':ag.space.Int(lower=3, upper=10),
    'learning_rate': ag.space.Real(lower=1e-4, upper=1e-1, log=True)
}

hyperparameters = {
                   'GBM': gbm_options,
                   'NN_TORCH': nn_options,
                   'CAT':cat_options,
                   'XGB':xg_options,
                  } 
num_trials =5
search_strategy = 'auto'

hyperparameter_tune_kwargs = {
    'num_trials': num_trials,
    'scheduler' : 'local',
    'searcher': search_strategy,
}
predictor = TabularPredictor(label="diagnosis", eval_metric='accuracy').fit(
    train_data, time_limit=1200,
    hyperparameters=hyperparameters, hyperparameter_tune_kwargs=hyperparameter_tune_kwargs,
)

Fitted model: NeuralNetTorch/d23c5f7a ...
	0.9815	 = Validation score   (accuracy)
	6.57s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: NeuralNetTorch/2c31f5ec ...
	0.9722	 = Validation score   (accuracy)
	9.95s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: NeuralNetTorch/08e9546d ...
	0.9815	 = Validation score   (accuracy)
	2.58s	 = Training   runtime
	0.09s	 = Validation runtime
Fitted model: NeuralNetTorch/7a636f71 ...
	0.9815	 = Validation score   (accuracy)
	2.16s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: NeuralNetTorch/955036cf ...
	0.9907	 = Validation score   (accuracy)
	1.06s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.0s of the 1148.54s of remaining time.
	0.9907	 = Validation score   (accuracy)
	1.2s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 52.72s ... Best model: "WeightedEnsemble_L2"
Ta

In [44]:
predictor.get_model_names()

['LightGBM/T1',
 'LightGBM/T2',
 'LightGBM/T3',
 'LightGBM/T4',
 'LightGBM/T5',
 'CatBoost/T1',
 'CatBoost/T2',
 'CatBoost/T3',
 'CatBoost/T4',
 'CatBoost/T5',
 'XGBoost/T1',
 'XGBoost/T2',
 'XGBoost/T3',
 'XGBoost/T4',
 'XGBoost/T5',
 'NeuralNetTorch/d23c5f7a',
 'NeuralNetTorch/2c31f5ec',
 'NeuralNetTorch/08e9546d',
 'NeuralNetTorch/7a636f71',
 'NeuralNetTorch/955036cf',
 'WeightedEnsemble_L2']

###results

In [45]:
train_data

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          9.876         19.40           63.95      298.3          0.10050   
1         12.770         21.41           82.02      507.4          0.08749   
2         16.350         23.29          109.00      840.4          0.09742   
3         11.140         14.07           71.24      384.6          0.07274   
4         12.470         17.31           80.45      480.1          0.08928   
..           ...           ...             ...        ...              ...   
533       20.440         21.78          133.80     1293.0          0.09150   
534       15.220         30.62          103.40      716.9          0.10480   
535       17.460         39.28          113.40      920.6          0.09812   
536       15.460         23.95          103.80      731.3          0.11830   
537       23.290         26.67          158.90     1685.0          0.11410   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.09697         0.06154              0.03029         0.1945   
1             0.06601         0.03112              0.02864         0.1694   
2             0.14970         0.18110              0.08773         0.2175   
3             0.06064         0.04505              0.01471         0.1690   
4             0.07630         0.03609              0.02369         0.1526   
..                ...             ...                  ...            ...   
533           0.11310         0.09799              0.07785         0.1618   
534           0.20870         0.25500              0.09429         0.2128   
535           0.12980         0.14170              0.08811         0.1809   
536           0.18700         0.20300              0.08520         0.1807   
537           0.20840         0.35230              0.16200         0.2200   

     fractal_dimension_mean  ...  texture_worst  perimeter_worst  area_worst  \
0                   0.06322  ...          26.83            72.22       361.2   
1                   0.06287  ...          23.50            89.04       579.5   
2                   0.06218  ...          31.03           129.30      1165.0   
3                   0.06083  ...          15.82            79.62       453.5   
4                   0.06046  ...          24.34            92.82       607.3   
..                      ...  ...            ...              ...         ...   
533                 0.05557  ...          26.37           161.20      1780.0   
534                 0.07152  ...          42.79           128.70       915.0   
535                 0.05966  ...          44.87           141.20      1408.0   
536                 0.07083  ...          36.33           117.70       909.4   
537                 0.06229  ...          32.68           177.00      1986.0   

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.15590            0.23020          0.26440   
1             0.09388            0.08978          0.05186   
2             0.14150            0.46650          0.70870   
3             0.08864            0.12560          0.12010   
4             0.12760            0.25060          0.20280   
..                ...                ...              ...   
533           0.13270            0.23760          0.27020   
534           0.14170            0.79170          1.17000   
535           0.13650            0.37350          0.32410   
536           0.17320            0.49670          0.59110   
537           0.15360            0.41670          0.78920   

     concave points_worst  symmetry_worst  fractal_dimension_worst  diagnosis  
0                 0.09749          0.2622                  0.08490          0  
1                 0.04773          0.2179                  0.06871          0  
2                 0.22480          0.4824                  0.09614          1  
3                 0.03922          0.2576                  0.07018          0  
4                 0.10530          0.3035        

In [46]:
#try chance model from predictor , the results are feature_importance top 10 do not the same even the same model.
name=predictor.get_model_names()[15]
print(name)
top10_importance_feature_TNN=predictor.feature_importance(train_data,model=name).head(10)
top10_importance_feature_TNN

Computing feature importance via permutation shuffling for 30 features using 538 rows with 5 shuffle sets...
	4.93s	= Expected runtime (0.99s per shuffle set)


NeuralNetTorch/d23c5f7a


	0.83s	= Actual runtime (Completed 5 of 5 shuffle sets)


importance    stddev   p_value  n  p99_high   p99_low
texture_worst           0.013383  0.004239  0.001061  5  0.022110  0.004656
radius_worst            0.013383  0.005936  0.003638  5  0.025606  0.001160
concavity_worst         0.012268  0.006385  0.006342  5  0.025414 -0.000879
concave points_worst    0.011152  0.005257  0.004507  5  0.021977  0.000328
perimeter_mean          0.010409  0.004847  0.004318  5  0.020389  0.000429
perimeter_worst         0.009294  0.004359  0.004429  5  0.018269  0.000318
fractal_dimension_se    0.009294  0.002276  0.000399  5  0.013981  0.004606
symmetry_worst          0.009294  0.003477  0.001970  5  0.016454  0.002134
area_se                 0.009294  0.002939  0.001055  5  0.015345  0.003242
area_worst              0.008922  0.003325  0.001941  5  0.015768  0.002076

In [47]:
top10_importance_feature_TNN=train_data[top10_importance_feature_TNN.index.to_list()]
top10_importance_feature_TNN

texture_worst  radius_worst  concavity_worst  concave points_worst  \
0            26.83         10.76          0.26440               0.09749   
1            23.50         13.75          0.05186               0.04773   
2            31.03         19.38          0.70870               0.22480   
3            15.82         12.12          0.12010               0.03922   
4            24.34         14.06          0.20280               0.10530   
..             ...           ...              ...                   ...   
533          26.37         24.31          0.27020               0.17650   
534          42.79         17.52          1.17000               0.23560   
535          44.87         22.51          0.32410               0.20660   
536          36.33         17.11          0.59110               0.21630   
537          32.68         25.12          0.78920               0.27330   

     perimeter_mean  perimeter_worst  fractal_dimension_se  symmetry_worst  \
0             63.95            72.22              0.003570          0.2622   
1             82.02            89.04              0.005875          0.2179   
2            109.00           129.30              0.004085          0.4824   
3             71.24            79.62              0.004831          0.2576   
4             80.45            92.82              0.001541          0.3035   
..              ...              ...                   ...             ...   
533          133.80           161.20              0.001906          0.2609   
534          103.40           128.70              0.006142          0.4089   
535          113.40           141.20              0.002759          0.2853   
536          103.80           117.70              0.006000          0.3013   
537          158.90           177.00              0.005195          0.3198   

     area_se  area_worst  
0      11.77       361.2  
1      53.65       579.5  
2      45.50      1165.0  
3      28.84       453.5  
4      11.91       607.3  
..       ...         ...  
533    72.44      1780.0  
534    22.65       915.0  
535    49.00      1408.0  
536    32.52       909.4  
537    83.16      1986.0  

[538 rows x 10 columns]

In [48]:
test_data_nolabel=df_test.drop("diagnosis",axis=1)
y_pred = predictor.predict(test_data_nolabel)

In [49]:
#on the WeightedEnsemble_L2
print(accuracy_score(y_true,y_pred))

0.9790209790209791


In [50]:
results = predictor.fit_summary()

*** Summary of fit() ***
Estimated performance of each model:
                      model  score_val  pred_time_val  fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0   NeuralNetTorch/955036cf   0.990741       0.046464  1.057341                0.046464           1.057341            1       True         20
1       WeightedEnsemble_L2   0.990741       0.047415  2.257583                0.000951           1.200242            2       True         21
2   NeuralNetTorch/7a636f71   0.981481       0.017306  2.161415                0.017306           2.161415            1       True         19
3   NeuralNetTorch/d23c5f7a   0.981481       0.034244  6.566502                0.034244           6.566502            1       True         16
4   NeuralNetTorch/08e9546d   0.981481       0.094481  2.581385                0.094481           2.581385            1       True         18
5               CatBoost/T3   0.972222       0.001047  0.879747                0.00104

In [51]:
predictor.get_model_best()

'WeightedEnsemble_L2'

In [52]:
def create_result_df(fyt,fxt):
  model_to_use=[]
  acc=[]
  pre=[]
  rec=[]
  roc_auc_list=[]
  f1_macro=[]
  for i in range(len(predictor.get_model_names())):
    model_to_use.append(predictor.get_model_names()[i])
    model_pred = predictor.predict(fxt, model=model_to_use[i])
    acc.append(accuracy_score(fyt,model_pred))
    pre.append(precision_score(fyt,model_pred))
    rec.append(recall_score(fyt,model_pred))
    roc_auc_list.append(roc_auc_score(fyt,model_pred))
    f1_macro.append(f1_score(fyt,model_pred,average="binary"))
  return pd.DataFrame({"model_name":model_to_use,"accuracy":acc,"precision":pre,"recall":rec,"roc_auc":roc_auc_list,"f1_binary":f1_macro})

In [53]:
create_result_df(y_true,test_data_nolabel)

model_name  accuracy  precision    recall   roc_auc  \
0               LightGBM/T1  0.972028   1.000000  0.927273  0.963636   
1               LightGBM/T2  0.986014   1.000000  0.963636  0.981818   
2               LightGBM/T3  0.972028   1.000000  0.927273  0.963636   
3               LightGBM/T4  0.979021   1.000000  0.945455  0.972727   
4               LightGBM/T5  0.965035   1.000000  0.909091  0.954545   
5               CatBoost/T1  0.993007   0.982143  1.000000  0.994318   
6               CatBoost/T2  0.993007   0.982143  1.000000  0.994318   
7               CatBoost/T3  0.972028   0.947368  0.981818  0.973864   
8               CatBoost/T4  0.993007   0.982143  1.000000  0.994318   
9               CatBoost/T5  0.993007   0.982143  1.000000  0.994318   
10               XGBoost/T1  0.937063   0.925926  0.909091  0.931818   
11               XGBoost/T2  0.958042   0.980392  0.909091  0.948864   
12               XGBoost/T3  0.958042   0.962264  0.927273  0.952273   
13               XGBoost/T4  0.986014   0.981818  0.981818  0.985227   
14               XGBoost/T5  0.972028   0.963636  0.963636  0.970455   
15  NeuralNetTorch/d23c5f7a  0.986014   0.981818  0.981818  0.985227   
16  NeuralNetTorch/2c31f5ec  0.986014   0.964912  1.000000  0.988636   
17  NeuralNetTorch/08e9546d  0.972028   0.947368  0.981818  0.973864   
18  NeuralNetTorch/7a636f71  0.986014   1.000000  0.963636  0.981818   
19  NeuralNetTorch/955036cf  0.979021   0.948276  1.000000  0.982955   
20      WeightedEnsemble_L2  0.979021   0.948276  1.000000  0.982955   

    f1_binary  
0    0.962264  
1    0.981481  
2    0.962264  
3    0.971963  
4    0.952381  
5    0.990991  
6    0.990991  
7    0.964286  
8    0.990991  
9    0.990991  
10   0.917431  
11   0.943396  
12   0.944444  
13   0.981818  
14   0.963636  
15   0.981818  
16   0.982143  
17   0.964286  
18   0.981481  
19   0.973451  
20   0.973451



##7:2'nd try normal ways

In [54]:
#we got balanced folds: f1,f2,f3,f4,f5
#we got test : df_test
#f1[0] is training_set, f1[1] is validation_set

#from the 7:1'st 
#we know that
#1.XGBoost,CatBoost and lightGBM are the state of the art models
#2.ensemble work
#3.do not select importance feature > dynamical feature selection > importance feature selection

In [55]:
!pip install catboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


###catboost 😻

In [56]:
import catboost

####train with normal train,test set

In [57]:
y_true=df_test["diagnosis"]
test_data_nolabel=df_test.drop("diagnosis",axis=1)

In [58]:
def create_result_df(fyt,fxt,model):
  acc=[]
  pre=[]
  rec=[]
  roc_auc_list=[]
  f1_macro=[]
  model_pred =model.predict(fxt)
  acc.append(accuracy_score(fyt,model_pred))
  pre.append(precision_score(fyt,model_pred))
  rec.append(recall_score(fyt,model_pred))
  roc_auc_list.append(roc_auc_score(fyt,model_pred))
  f1_macro.append(f1_score(fyt,model_pred,average="binary"))
  print(confusion_matrix(fyt,model_pred))
  return pd.DataFrame({"accuracy":acc,"precision":pre,"recall":rec,"roc_auc":roc_auc_list,"f1_binary":f1_macro}),model_pred

In [59]:
#normally train with pd.DataFrame
train_cat=df_train.drop("diagnosis",axis=1)
cat_clf1=catboost.CatBoostClassifier(iterations=30,learning_rate=0.3,depth=6)
cat_clf1.fit(train_cat,df_train["diagnosis"])
cat1_pred=cat_clf1.predict(test_data_nolabel)
cat_res_df,cat_pred=create_result_df(y_true,test_data_nolabel,cat_clf1)
cat_res_df

0:	learn: 0.3573435	total: 15ms	remaining: 435ms
1:	learn: 0.2073477	total: 33.2ms	remaining: 464ms
2:	learn: 0.1452590	total: 48.7ms	remaining: 438ms
3:	learn: 0.1144898	total: 62.1ms	remaining: 404ms
4:	learn: 0.0878578	total: 70.5ms	remaining: 352ms
5:	learn: 0.0744997	total: 80.7ms	remaining: 323ms
6:	learn: 0.0573493	total: 91.2ms	remaining: 300ms
7:	learn: 0.0485860	total: 98.7ms	remaining: 271ms
8:	learn: 0.0427654	total: 108ms	remaining: 253ms
9:	learn: 0.0386595	total: 118ms	remaining: 236ms
10:	learn: 0.0345583	total: 126ms	remaining: 218ms
11:	learn: 0.0305139	total: 135ms	remaining: 202ms
12:	learn: 0.0271324	total: 145ms	remaining: 189ms
13:	learn: 0.0243051	total: 158ms	remaining: 180ms
14:	learn: 0.0212592	total: 170ms	remaining: 170ms
15:	learn: 0.0194598	total: 185ms	remaining: 162ms
16:	learn: 0.0179710	total: 205ms	remaining: 157ms
17:	learn: 0.0166152	total: 220ms	remaining: 147ms
18:	learn: 0.0155620	total: 235ms	remaining: 136ms
19:	learn: 0.0144604	total: 249ms	r

accuracy  precision  recall   roc_auc  f1_binary
0  0.979021   0.948276     1.0  0.982955   0.973451

In [60]:
importance =cat_clf1.get_feature_importance()
importance

array([4.67125975, 3.82533387, 5.89848967, 3.26802637, 0.95407969,
       1.55508024, 3.06088612, 7.99750801, 3.28264864, 0.33789474,
       1.36652559, 1.9395668 , 0.51174894, 7.22154939, 0.05066313,
       2.34665056, 1.72382254, 1.00767057, 2.98353661, 1.18132564,
       0.64230795, 8.74172901, 8.59919232, 2.95916729, 3.49992454,
       0.45273086, 8.59903678, 7.17122339, 1.90223103, 2.24818994])

In [61]:
train_cat.columns

Index(['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean',
       'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [62]:
feature_importance_on_cat=pd.DataFrame({"feature":train_cat.columns,"importance":importance})

In [63]:
top_10_cat_feature=feature_importance_on_cat.sort_values("importance",ascending=False).head(10)
top_10_cat_feature

feature  importance
21         texture_worst    8.741729
22       perimeter_worst    8.599192
26       concavity_worst    8.599037
7    concave points_mean    7.997508
13               area_se    7.221549
27  concave points_worst    7.171223
2         perimeter_mean    5.898490
0            radius_mean    4.671260
1           texture_mean    3.825334
24      smoothness_worst    3.499925

In [64]:
#after using to 10 feature important
cat_clf2=catboost.CatBoostClassifier(iterations=30,learning_rate=0.3,depth=6)
cat_clf2.fit(train_cat[top_10_cat_feature.feature.to_list()],df_train["diagnosis"])
cat2_pred=cat_clf2.predict(test_data_nolabel)
cat2_res_df,cat2_pred=create_result_df(y_true,test_data_nolabel,cat_clf2)
cat2_res_df

0:	learn: 0.5214116	total: 10.2ms	remaining: 297ms
1:	learn: 0.4079285	total: 17.9ms	remaining: 251ms
2:	learn: 0.3240318	total: 24.5ms	remaining: 220ms
3:	learn: 0.2684330	total: 34.4ms	remaining: 224ms
4:	learn: 0.2280273	total: 41.4ms	remaining: 207ms
5:	learn: 0.1956413	total: 45.3ms	remaining: 181ms
6:	learn: 0.1714370	total: 54ms	remaining: 178ms
7:	learn: 0.1527684	total: 58.6ms	remaining: 161ms
8:	learn: 0.1363672	total: 62.4ms	remaining: 146ms
9:	learn: 0.1224568	total: 69.3ms	remaining: 139ms
10:	learn: 0.1127970	total: 72.2ms	remaining: 125ms
11:	learn: 0.1031815	total: 76.2ms	remaining: 114ms
12:	learn: 0.0940552	total: 82.8ms	remaining: 108ms
13:	learn: 0.0871053	total: 93.5ms	remaining: 107ms
14:	learn: 0.0807220	total: 102ms	remaining: 102ms
15:	learn: 0.0759208	total: 107ms	remaining: 94ms
16:	learn: 0.0718053	total: 111ms	remaining: 85.2ms
17:	learn: 0.0679748	total: 115ms	remaining: 76.7ms
18:	learn: 0.0649283	total: 119ms	remaining: 69ms
19:	learn: 0.0621884	total: 1

accuracy  precision    recall   roc_auc  f1_binary
0  0.986014   0.981818  0.981818  0.985227   0.981818

##### result non importance features vs important feature

In [65]:
confusion_matrix(y_true,cat2_pred),confusion_matrix(y_true,cat1_pred)

(array([[87,  1],
        [ 1, 54]]),
 array([[85,  3],
        [ 0, 55]]))

####train with k-fold

In [66]:
x_train.iloc[list(f1[0])]

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          9.876         19.40           63.95      298.3          0.10050   
1         12.770         21.41           82.02      507.4          0.08749   
2         16.350         23.29          109.00      840.4          0.09742   
4         12.470         17.31           80.45      480.1          0.08928   
5         13.590         21.84           87.16      561.0          0.07956   
..           ...           ...             ...        ...              ...   
532       20.090         23.86          134.70     1247.0          0.10800   
533       20.440         21.78          133.80     1293.0          0.09150   
534       15.220         30.62          103.40      716.9          0.10480   
535       17.460         39.28          113.40      920.6          0.09812   
537       23.290         26.67          158.90     1685.0          0.11410   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.09697         0.06154              0.03029         0.1945   
1             0.06601         0.03112              0.02864         0.1694   
2             0.14970         0.18110              0.08773         0.2175   
4             0.07630         0.03609              0.02369         0.1526   
5             0.08259         0.04072              0.02142         0.1635   
..                ...             ...                  ...            ...   
532           0.18380         0.22830              0.12800         0.2249   
533           0.11310         0.09799              0.07785         0.1618   
534           0.20870         0.25500              0.09429         0.2128   
535           0.12980         0.14170              0.08811         0.1809   
537           0.20840         0.35230              0.16200         0.2200   

     fractal_dimension_mean  ...  texture_worst  perimeter_worst  area_worst  \
0                   0.06322  ...          26.83            72.22       361.2   
1                   0.06287  ...          23.50            89.04       579.5   
2                   0.06218  ...          31.03           129.30      1165.0   
4                   0.06046  ...          24.34            92.82       607.3   
5                   0.05859  ...          30.04            97.66       661.5   
..                      ...  ...            ...              ...         ...   
532                 0.07469  ...          29.43           158.80      1696.0   
533                 0.05557  ...          26.37           161.20      1780.0   
534                 0.07152  ...          42.79           128.70       915.0   
535                 0.05966  ...          44.87           141.20      1408.0   
537                 0.06229  ...          32.68           177.00      1986.0   

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.15590            0.23020          0.26440   
1             0.09388            0.08978          0.05186   
2             0.14150            0.46650          0.70870   
4             0.12760            0.25060          0.20280   
5             0.10050            0.17300          0.14530   
..                ...                ...              ...   
532           0.13470            0.33910          0.49320   
533           0.13270            0.23760          0.27020   
534           0.14170            0.79170          1.17000   
535           0.13650            0.37350          0.32410   
537           0.15360            0.41670          0.78920   

     concave points_worst  symmetry_worst  fractal_dimension_worst  diagnosis  
0                 0.09749          0.2622                  0.08490          0  
1                 0.04773          0.2179                  0.06871          0  
2                 0.22480          0.4824                  0.09614          1  
4                 0.10530          0.3035                  0.07661          0  
5                 0.06189          0.2446        

##### train_k_fold and test function

In [67]:
#we got list_folf =[f1,f2,f3,f4,f5]
def train_k_fold_and_test(model,list_fold,x_train,y_train):
  acc=[]
  pre=[]
  rec=[]
  roc_auc_list=[]
  f1_macro=[]
  model=model
  for fold in list_fold:
    model.fit(x_train.iloc[fold[0]],y_train.iloc[fold[0]])
    model_pred=model.predict(x_train.iloc[fold[1]])
    acc.append(accuracy_score(y_train.iloc[fold[1]],model_pred))
    pre.append(precision_score(y_train.iloc[fold[1]],model_pred))
    rec.append(recall_score(y_train.iloc[fold[1]],model_pred))
    roc_auc_list.append(roc_auc_score(y_train.iloc[fold[1]],model_pred))
    f1_macro.append(f1_score(y_train.iloc[fold[1]],model_pred,average="binary"))
  return pd.DataFrame({"accuracy":acc,"precision":pre,"recall":rec,"roc_auc":roc_auc_list,"f1_binary":f1_macro}),create_result_df(y_true,test_data_nolabel,model)

In [68]:
cat_clf3=catboost.CatBoostClassifier(iterations=30,learning_rate=0.3,depth=6)
result_k_fold,cat3_res_df=train_k_fold_and_test(cat_clf3,list_fold,x_train.drop(["diagnosis"],axis=1),y_train)
%timeit train_k_fold_and_test(cat_clf3,list_fold,x_train.drop(["diagnosis"],axis=1),y_train)

0:	learn: 0.3617428	total: 9.49ms	remaining: 275ms
1:	learn: 0.2282408	total: 19.6ms	remaining: 274ms
2:	learn: 0.1563052	total: 30ms	remaining: 270ms
3:	learn: 0.1143386	total: 38.8ms	remaining: 252ms
4:	learn: 0.0871339	total: 47.7ms	remaining: 238ms
5:	learn: 0.0758792	total: 56.4ms	remaining: 226ms
6:	learn: 0.0643796	total: 64.3ms	remaining: 211ms
7:	learn: 0.0508163	total: 73.7ms	remaining: 203ms
8:	learn: 0.0416198	total: 82.9ms	remaining: 193ms
9:	learn: 0.0376570	total: 91.2ms	remaining: 182ms
10:	learn: 0.0308133	total: 101ms	remaining: 174ms
11:	learn: 0.0261025	total: 109ms	remaining: 163ms
12:	learn: 0.0228924	total: 118ms	remaining: 154ms
13:	learn: 0.0198301	total: 130ms	remaining: 148ms
14:	learn: 0.0182791	total: 146ms	remaining: 146ms
15:	learn: 0.0166455	total: 161ms	remaining: 141ms
16:	learn: 0.0157774	total: 176ms	remaining: 134ms
17:	learn: 0.0150354	total: 191ms	remaining: 127ms
18:	learn: 0.0140634	total: 210ms	remaining: 121ms
19:	learn: 0.0131182	total: 233ms

#####results

In [69]:
result_k_fold

accuracy  precision    recall   roc_auc  f1_binary
0  0.972222   0.981132  0.962963  0.972222   0.971963
1  0.962963   0.962963  0.962963  0.962963   0.962963
2  0.953704   0.945455  0.962963  0.953704   0.954128
3  0.990654   1.000000  0.981132  0.990566   0.990476
4  0.981308   1.000000  0.962963  0.981481   0.981132

In [70]:
cat3_res_df[0],cat3_res_df[1]

(   accuracy  precision  recall   roc_auc  f1_binary
 0  0.993007   0.982143     1.0  0.994318   0.990991,
 array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
        0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
        0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0]))

###lgbm 🎄

In [71]:
!pip install lightgbm

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [72]:
import lightgbm as lgb

In [73]:
lgb.__version__

'3.3.5'

#### train with normal train,test

In [74]:
lgb_clf=lgb.LGBMClassifier(boosting_type='gbdt',num_leaves=31,max_depth=-1,learninf_rate=0.1,random_state=115)

In [75]:
lgb_clf.fit(x_train.drop("diagnosis",axis=1), y_train)
%timeit lgb_clf.fit(x_train.drop("diagnosis",axis=1), y_train)

[LightGBM] [Warning] Unknown parameter: learninf_rate
321 ms ± 187 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


##### result non importance feature vs importance feature

In [76]:
lgb_res_df,lgb_pred=create_result_df(y_true,test_data_nolabel,lgb_clf)
lgb_res_df

[[88  0]
 [ 4 51]]


accuracy  precision    recall   roc_auc  f1_binary
0  0.972028        1.0  0.927273  0.963636   0.962264

In [77]:
lgb_importance=lgb_clf.feature_importances_
feature_importance_on_lgb=pd.DataFrame({"feature":x_train.drop("diagnosis",axis=1).columns,"importance":lgb_importance})
feature_importance_on_lgb_top10=feature_importance_on_lgb.sort_values("importance",ascending=False).head(10)
feature_importance_on_lgb_top10

feature  importance
21         texture_worst         234
27  concave points_worst         207
7    concave points_mean         168
22       perimeter_worst         152
1           texture_mean         150
20          radius_worst         120
28        symmetry_worst         111
13               area_se         103
26       concavity_worst         101
15        compactness_se          96

In [78]:
#after using to 10 feature important
lgb_clf2=lgb.LGBMClassifier(boosting_type='gbdt',num_leaves=31,max_depth=-1,learninf_rate=0.1,random_state=115)
lgb_clf2.fit(x_train.drop("diagnosis",axis=1)[feature_importance_on_lgb_top10.feature.to_list()],y_train)
lgb2_res_df,lgb2_pred=create_result_df(y_true,test_data_nolabel[feature_importance_on_lgb_top10.feature.to_list()],lgb_clf2)
lgb2_res_df
%timeit lgb_clf2.fit(x_train.drop("diagnosis",axis=1)[feature_importance_on_lgb_top10.feature.to_list()],y_train)

[LightGBM] [Warning] Unknown parameter: learninf_rate
[[87  1]
 [ 1 54]]
[LightGBM] [Warning] Unknown parameter: learninf_rate
The slowest run took 4.60 times longer than the fastest. This could mean that an intermediate result is being cached.
222 ms ± 123 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


####train with k fold

In [79]:
lgb_clf2=lgb.LGBMClassifier(boosting_type='gbdt',num_leaves=31,max_depth=-1,learninf_rate=0.3,random_state=114,n_estimators=50)

##### results

In [80]:
result_k_fold,result_lgb_df=train_k_fold_and_test(lgb_clf2,list_fold,x_train.drop("diagnosis",axis=1),y_train)
%timeit train_k_fold_and_test(lgb_clf2,list_fold,x_train.drop("diagnosis",axis=1),y_train)

[LightGBM] [Warning] Unknown parameter: learninf_rate
[LightGBM] [Warning] Unknown parameter: learninf_rate
[LightGBM] [Warning] Unknown parameter: learninf_rate
[LightGBM] [Warning] Unknown parameter: learninf_rate
[[88  0]
 [ 0 55]]
[LightGBM] [Warning] Unknown parameter: learninf_rate
[LightGBM] [Warning] Unknown parameter: learninf_rate
[LightGBM] [Warning] Unknown parameter: learninf_rate
[LightGBM] [Warning] Unknown parameter: learninf_rate
[LightGBM] [Warning] Unknown parameter: learninf_rate
[[88  0]
 [ 0 55]]
[LightGBM] [Warning] Unknown parameter: learninf_rate
[LightGBM] [Warning] Unknown parameter: learninf_rate
[LightGBM] [Warning] Unknown parameter: learninf_rate
[LightGBM] [Warning] Unknown parameter: learninf_rate
[LightGBM] [Warning] Unknown parameter: learninf_rate
[[88  0]
 [ 0 55]]
[LightGBM] [Warning] Unknown parameter: learninf_rate
[LightGBM] [Warning] Unknown parameter: learninf_rate
[LightGBM] [Warning] Unknown parameter: learninf_rate
[LightGBM] [Warning] Unkn

In [81]:
result_k_fold

accuracy  precision    recall   roc_auc  f1_binary
0  0.972222   0.981132  0.962963  0.972222   0.971963
1  0.962963   0.962963  0.962963  0.962963   0.962963
2  0.916667   0.894737  0.944444  0.916667   0.918919
3  0.990654   1.000000  0.981132  0.990566   0.990476
4  0.990654   1.000000  0.981481  0.990741   0.990654

In [82]:
result_lgb_df[0],result_lgb_df[1]

(   accuracy  precision  recall  roc_auc  f1_binary
 0       1.0        1.0     1.0      1.0        1.0,
 array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
        0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
        0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0]))

### dicision trees

#### train with normal train,test

In [83]:
from Decision_trees import DecisionTree

In [84]:
DecisionTree

<module 'Decision_trees.DecisionTree' from '/content/Decision_trees/DecisionTree.py'>

In [85]:
dct_model=DecisionTree.DecisionTree(max_depth=7)

In [86]:
%timeit dct_model.fit(np.array(x_train.drop("diagnosis",axis=1)),np.array(y_train))

The slowest run took 4.65 times longer than the fastest. This could mean that an intermediate result is being cached.
8.52 s ± 4.88 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


#####results

In [87]:
dct_pred=dct_model.predict(np.array(df_test.drop("diagnosis",axis=1)))
dct_pred

array([0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0])

In [88]:
accuracy_score(y_true,dct_pred)

0.9370629370629371

In [89]:
confusion_matrix(y_true,dct_pred)

array([[83,  5],
       [ 4, 51]])

###torchNN from autogluon 🕯️

In [90]:
the_name_is=predictor.get_model_names()[15]
the_name_is

'NeuralNetTorch/d23c5f7a'

#####train with normal,test set

In [91]:
## เเก้ function ให้เหมาะกับ autogluon.predictor
def create_result_df_autogluon(fyt,fxt,predictor,model_name):
  acc=[]
  pre=[]
  rec=[]
  roc_auc_list=[]
  f1_macro=[]
  model_pred =predictor.predict(fxt,model=model_name)
  acc.append(accuracy_score(fyt,model_pred))
  pre.append(precision_score(fyt,model_pred))
  rec.append(recall_score(fyt,model_pred))
  roc_auc_list.append(roc_auc_score(fyt,model_pred))
  f1_macro.append(f1_score(fyt,model_pred,average="binary"))
  print(confusion_matrix(fyt,model_pred))
  return pd.DataFrame({"accuracy":acc,"precision":pre,"recall":rec,"roc_auc":roc_auc_list,"f1_binary":f1_macro}),model_pred

####result non importance feature vs important feature

In [92]:
top10_importance_feature_TNN=train_data[top10_importance_feature_TNN.columns.to_list()]
top10_importance_feature_TNN['diagnosis']=train_data['diagnosis']

SettingWithCopyError: ignored

In [93]:
top10_importance_feature_TNN=TabularDataset(top10_importance_feature_TNN)
top10_importance_feature_TNN

texture_worst  radius_worst  concavity_worst  concave points_worst  \
0            26.83         10.76          0.26440               0.09749   
1            23.50         13.75          0.05186               0.04773   
2            31.03         19.38          0.70870               0.22480   
3            15.82         12.12          0.12010               0.03922   
4            24.34         14.06          0.20280               0.10530   
..             ...           ...              ...                   ...   
533          26.37         24.31          0.27020               0.17650   
534          42.79         17.52          1.17000               0.23560   
535          44.87         22.51          0.32410               0.20660   
536          36.33         17.11          0.59110               0.21630   
537          32.68         25.12          0.78920               0.27330   

     perimeter_mean  perimeter_worst  fractal_dimension_se  symmetry_worst  \
0             63.95            72.22              0.003570          0.2622   
1             82.02            89.04              0.005875          0.2179   
2            109.00           129.30              0.004085          0.4824   
3             71.24            79.62              0.004831          0.2576   
4             80.45            92.82              0.001541          0.3035   
..              ...              ...                   ...             ...   
533          133.80           161.20              0.001906          0.2609   
534          103.40           128.70              0.006142          0.4089   
535          113.40           141.20              0.002759          0.2853   
536          103.80           117.70              0.006000          0.3013   
537          158.90           177.00              0.005195          0.3198   

     area_se  area_worst  diagnosis  
0      11.77       361.2          0  
1      53.65       579.5          0  
2      45.50      1165.0          1  
3      28.84       453.5          0  
4      11.91       607.3          0  
..       ...         ...        ...  
533    72.44      1780.0          1  
534    22.65       915.0          1  
535    49.00      1408.0          1  
536    32.52       909.4          1  
537    83.16      1986.0          1  

[538 rows x 11 columns]

In [94]:
nn_options = {
    'num_epochs': 10, 
    'learning_rate': ag.space.Real(1e-4, 1e-2, default=5e-4, log=True),
    'activation': ag.space.Categorical('relu'),
    'dropout_prob': ag.space.Real(0.0, 0.5, default=0.1)
}

hyperparameters = {
                   'NN_TORCH': nn_options,
                  } 
num_trials =1
search_strategy = 'auto'

hyperparameter_tune_kwargs = {
    'num_trials': num_trials,
    'scheduler' : 'local',
    'searcher': search_strategy,
}
predictor1 = TabularPredictor(label="diagnosis", eval_metric='accuracy').fit(
    top10_importance_feature_TNN, time_limit=1200,
    hyperparameters=hyperparameters, hyperparameter_tune_kwargs=hyperparameter_tune_kwargs,
)

Fitted model: NeuralNetTorch/f68ba5e4 ...
	0.9815	 = Validation score   (accuracy)
	2.82s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.0s of the 1192.8s of remaining time.
	0.9815	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 7.24s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20230512_160458/")


In [95]:
TNN_res_pd,TNN_pred=create_result_df_autogluon(y_true,test_data_nolabel,predictor,the_name_is)

[[87  1]
 [ 1 54]]


In [96]:
TNN_res_pd

accuracy  precision    recall   roc_auc  f1_binary
0  0.986014   0.981818  0.981818  0.985227   0.981818

In [97]:
TNN_res_pd1,TNN_pred1=create_result_df_autogluon(y_true,test_data_nolabel[top10_importance_feature_TNN.columns.to_list()[:10]],predictor1,predictor1.get_model_names()[0])

[[87  1]
 [ 1 54]]


In [98]:
TNN_res_pd1

accuracy  precision    recall   roc_auc  f1_binary
0  0.986014   0.981818  0.981818  0.985227   0.981818

##ensemble by majority voting 🗳️

In [99]:
from scipy import stats

In [100]:
cat3_pred=cat3_res_df[1]
cat3_pred

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0])

In [101]:
lgb_pred=result_lgb_df[1]
lgb_pred

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0])

In [102]:
tnn_pred=np.array(TNN_pred)
tnn_pred

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0])

In [103]:
ensemble = np.array([cat3_pred, lgb_pred, tnn_pred])

In [104]:
mode_ensemble = stats.mode(ensemble, axis=0)
mode_values = mode_ensemble.mode[0]

# print the mode values
print("Mode values:", mode_values)

Mode values: [0 0 1 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1 1 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0
 1 0 0 0 1 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 1 0 1 0 1 1 0 0 1 0
 0 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0]


<ipython-input-104-43edc0cf8064>:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode_ensemble = stats.mode(ensemble, axis=0)


In [105]:
confusion_matrix(y_true,mode_values)

array([[88,  0],
       [ 0, 55]])