<a href="https://colab.research.google.com/github/Augustus2001/Datascience/blob/main/first_tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
#kun kerdthaisong
#07/17/2022
#ref Laurence Moroney

#import tensorflow
import tensorflow as tf
print(tf.__version__)
#create callback
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self,epoch,logs={}):
    if(logs.get("accuracy")>0.95):
      print("\n reached 95% acc stop training")
      self.model.stop_training=True
callbacks=myCallback()
data=tf.keras.datasets.fashion_mnist

2.8.2


In [30]:
#load data from fashion_mnist
(train_images,train_labels),(test_images,test_labels)=data.load_data()

#change pixels in array between 0-255 to 0-1 ==this is calles normalize
train_images=train_images/255
test_images=test_images/255



In [31]:
#create model
model=tf.keras.models.Sequential([
                                  tf.keras.layers.Flatten(input_shape=(28,28)),#the input layer: change 2D 28x28 pixels to 1d
                                  tf.keras.layers.Dense(128,activation=tf.nn.relu), #hidden layer use 128 neurons(came randomly the more neurons the more acc the more time and overfit) and activate as relu
                                  tf.keras.layers.Dense(10,activation=tf.nn.softmax) #output layers use 10 neurons bcz there are 10 lebels 
])
#conclusion this architecture use 3 layers.



In [32]:
#define loss_function and optimizer
model.compile(optimizer="adam",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])


In [33]:

#traning
model.fit(train_images,train_labels,epochs=60,callbacks=[callbacks])

Epoch 1/60
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4941 - accuracy: 0.8260
Epoch 2/60
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3741 - accuracy: 0.8647
Epoch 3/60
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3353 - accuracy: 0.8773
Epoch 4/60
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3141 - accuracy: 0.8844
Epoch 5/60
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2953 - accuracy: 0.8905
Epoch 6/60
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2820 - accuracy: 0.8957
Epoch 7/60
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2677 - accuracy: 0.8996
Epoch 8/60
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2565 - accuracy: 0.9050
Epoch 9/60
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2467 - accuracy: 0.9078
Epoch 10/60
1875/1875 [==============================] - 4s 2ms/step - loss: 0.237

In [37]:
#evaluation
model.evaluate(test_images,test_labels)

313/313 [==============================] - 0s 1ms/step - loss: 0.4211 - accuracy: 0.8848


[0.42111504077911377, 0.8848000168800354]

In [72]:
#sample testing
import numpy as np
result=model.predict(test_images)
print(result[0])
print(test_labels[0])
for i,j in enumerate(test_labels[0:10]):
  print(np.where(result[i]==result[i].max()),j)

[3.0128534e-15 3.0251199e-14 5.8392376e-15 2.4421676e-20 3.2350306e-17
 1.1726775e-08 9.8431810e-15 2.9038129e-05 5.5351237e-16 9.9997091e-01]
9
(array([9]),) 9
(array([2]),) 2
(array([1]),) 1
(array([1]),) 1
(array([6]),) 6
(array([1]),) 1
(array([4]),) 4
(array([6]),) 6
(array([5]),) 5
(array([7]),) 7
