<a href="https://colab.research.google.com/github/Augustus2001/Datascience/blob/main/first_tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [105]:
#kun kerdthaisong
#07/17/2022
#ref Laurence Moroney

#import tensorflow
import tensorflow as tf
print(tf.__version__)
#create callback
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self,epoch,logs={}):
    if(logs.get("accuracy")>0.95):
      print("\n reached 0.89% acc stop training")
      self.model.stop_training=True
callbacks=myCallback()
data=tf.keras.datasets.fashion_mnist

2.8.2


In [106]:
#load data from fashion_mnist
(train_images,train_labels),(test_images,test_labels)=data.load_data()
#reshape to prepare cnn
print(train_images.shape)
train_images=train_images.reshape(60000,28,28,1)
test_images=test_images.reshape(10000,28,28,1)
#change pixels in array between 0-255 to 0-1 ==this is calles normalize
train_images=train_images/255
test_images=test_images/255



(60000, 28, 28)


In [107]:
from tensorflow.python.ops.gen_nn_ops import Conv2D
#create model
model=tf.keras.models.Sequential([
                                  tf.keras.layers.Conv2D(64,(2,2),activation='relu',input_shape=(28,28,1)), #add Cnn 
                                  tf.keras.layers.MaxPool2D(pool_size=(2,2)), #max pool
                                  tf.keras.layers.Conv2D(64,(2,2),activation='relu',input_shape=(28,28,1)),
                                  tf.keras.layers.MaxPool2D(pool_size=(2,2)),
                                  tf.keras.layers.Flatten(),#the input layer: change 2D 28x28 pixels to 1d
                                  tf.keras.layers.Dense(128,activation=tf.nn.relu), #hidden layer use 128 neurons(came randomly the more neurons the more acc the more time and overfit) and activate as relu
                                  tf.keras.layers.Dense(10,activation=tf.nn.softmax) #output layers use 10 neurons bcz there are 10 lebels 
])
#conclusion this architecture use 3 layers.



In [108]:
#define loss_function and optimizer
model.compile(optimizer="adam",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])


In [109]:

#traning
model.fit(train_images,train_labels,epochs=20,callbacks=[callbacks])

Epoch 1/20
1875/1875 [==============================] - 77s 41ms/step - loss: 0.4233 - accuracy: 0.8450
Epoch 2/20
1875/1875 [==============================] - 76s 40ms/step - loss: 0.2876 - accuracy: 0.8942
Epoch 3/20
1875/1875 [==============================] - 75s 40ms/step - loss: 0.2446 - accuracy: 0.9089
Epoch 4/20
1875/1875 [==============================] - 76s 41ms/step - loss: 0.2127 - accuracy: 0.9208
Epoch 5/20
1875/1875 [==============================] - 75s 40ms/step - loss: 0.1849 - accuracy: 0.9298
Epoch 6/20
1875/1875 [==============================] - 73s 39ms/step - loss: 0.1614 - accuracy: 0.9392
Epoch 7/20
1875/1875 [==============================] - 73s 39ms/step - loss: 0.1398 - accuracy: 0.9476
Epoch 8/20
1874/1875 [============================>.] - ETA: 0s - loss: 0.1210 - accuracy: 0.9543
 reached 0.89% acc stop training
1875/1875 [==============================] - 73s 39ms/step - loss: 0.1210 - accuracy: 0.9543


In [110]:
#evaluation
model.evaluate(test_images,test_labels)

313/313 [==============================] - 4s 12ms/step - loss: 0.2538 - accuracy: 0.9174


[0.2537848651409149, 0.9174000024795532]

In [111]:
#sample testing
import numpy as np
result=model.predict(test_images)
print(result[0])
print(test_labels[0])
for i,j in enumerate(test_labels[0:10]):
  print(np.where(result[i]==result[i].max()),j)

[4.3848991e-09 2.4452383e-08 7.5883527e-10 5.0525475e-08 2.0840864e-10
 4.5618503e-06 3.3027042e-10 1.3197164e-04 2.0492013e-11 9.9986339e-01]
9
(array([9]),) 9
(array([2]),) 2
(array([1]),) 1
(array([1]),) 1
(array([6]),) 6
(array([1]),) 1
(array([4]),) 4
(array([6]),) 6
(array([5]),) 5
(array([7]),) 7
